export const SET_ITEMS = "SET_ITEMS"
export const SET_SEARCH = "SET_SEARCH"
export const TOGGLE_FILTER = "TOGGLE_FILTER"
export const RESET_FILTERS = "RESET_FILTERS"
export const SET_PRICE_RANGE = "SET_PRICE_RANGE"
export const INCREMENT_PAGE = "INCREMENT_PAGE"
export const SET_PAGE = "SET_PAGE"
